#!/usr/bin/perl
#use Term::ANSIColor qw(:constants);
#use File::Path;
#$Term::ANSIColor::AUTORESET = 1;
#
# Run log file  
#
# Usage: NA
# 
# Noel Lacson, November 12, 2019
#                                        
#

my $rccmd =system("rclone listremotes");
my $cmd ="rclone copy ";
#my $c = "sudo scp ";
#system('clear');
print "Please wait....\n";
print $rccmd;
#my $lista="loglist";
#open(FILE,"<$lista") || die "File not found";
#chomp(my @script = <FILE>);

#foreach my $s (@script){
#system("$c$s $site >/dev/null");
#}
#system("zip -r $site.zip $site >/dev/null");
#sub remove
#{
    #my $dir = "$site";
    #rmtree $dir;

#}
sleep(5);
#my $log = system("sudo rclone copy $site.zip googleDrive:tmologs");

#system("rclone mkdir googleDrive:tmologs");

#sleep(5);
#print $log;
#system("$log >/dev/null");

print "Completed Thank you...";
sleep(5);

#remove();
exit(0);
